# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'PrivateConnection'
    subscriptionId: '169d3d90-e414-48c1-991f-14ec2bbaf9cd'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'testRG'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/fasih-ur-khan/test/master/CreateStorage.json'
    overrideParameters: |
      -storageAccountName "khanfasih897677"
      -location "West Europe"
      -storageSKU "Standard_LRS"
    deploymentMode: 'Incremental'
    deploymentName: 'mytestdep'